# This is a configuration file for Black (Python formatter)
# Should be located at project's root directory (`.git/` location)

[tool.black]
py36 = true
line-length = 80
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist

  # The following are specific to Black,
  # you probably don't want those.
  | blib2to3
  | tests/data
)/
'''