#!/usr/bin/env bash

#
# Aliases
#
alias c='cd ~/code; ls;'
alias d='cd ~/Downloads; ls;'
alias grep='grep --color=auto'
alias gg='grep --color=auto -rnwi . -e'
alias file_count='find . -type f | wc -l'

unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then
    double_click='xdg-open'
    alias ls='ls -lGF --color=auto'
    alias lsall='ls -flaF --color=auto'
elif [[ "$unamestr" == 'Darwin' ]]; then
    alias ls='ls -lGF'
    alias lsall='ls -flaF'
fi

#
# R
#
alias R='R --no-save'
alias r='R --no-save'
export R_PROFILE_USER='~/code/system/dotfiles/r/Rprofile'

#
# Bash-It
#
export BASH_IT=$HOME/.bash_it
export BASH_IT_THEME='otrenav'
if [ -e $BASH_IT/bash_it.sh ]; then
    source $BASH_IT/bash_it.sh
fi
HISTCONTROL=ignoredups:ignorespace

#
# Git
#
source ~/code/system/dotfiles/git/git-completion.bash

#
# Google Cloud
#
export CLOUDSDK_PYTHON=/usr/bin/python2.7
if [ -e ~/code/system/google-cloud/completion.bash.inc ]; then
    source ~/code/system/google-cloud/path.bash.inc
    source ~/code/system/google-cloud/completion.bash.inc
fi

#
# Emacs
#
if [[ "$unamestr" == 'Linux' ]]; then
    export ALTERNATE_EDITOR="code -n"
    export EDITOR="code -n"
elif [[ "$unamestr" == 'Darwin' ]]; then
    alias emacs='/Applications/Emacs.app/Contents/MacOS/Emacs'
    export EDITOR="code -n"
fi

#
# MySQL
#
function switch_database() {
    echo "[+] Switching database ($1)..."
    mysql -u root -p -e "DROP DATABASE $1";
    mysql -u root -p -e "CREATE DATABASE $1 CHARACTER SET UTF8;";
    mysql -u root -p $1 < $2
    echo "[+] Done."
}

#
# Python
#
alias kp='killall python'
alias rm_pyc='find . -name "*.pyc" -exec rm {} \;'
alias ae='deactivate &> /dev/null; source ./.venv/bin/activate'
alias me='python3 -m venv .venv'
alias re='rm -rf ./.venv/'
alias de='deactivate'

#
# Django
#
alias m='./manage.py'
alias dj='./manage.py runserver'
alias ds='./manage.py shell_plus'
alias rm_migrations='find . -name "000*.py*" -exec rm {} \;'

#
# Functions
#
function file_directory_size() {
    if du -b /dev/null > /dev/null 2>&1; then
        local arg=-sbh
    else
        local arg=-sh
    fi
    if [[ -n "$@" ]]; then
        du $arg -- "$@"
    else
        du $arg .[^.]* *
    fi
}

function show_keys() {
    gpg $1
    f=$(echo $1 | sed 's/\.[^.]*$//')
    more "${f}"
    rm "${f}"
}

#
# AWS
#
alias dynamodb='java -Djava.library.path=~/Applications/DynamoDB/DynamoDBLocal_lib -jar ~/Applications/DynamoDB/DynamoDBLocal.jar -sharedDb'
