#!/usr/bin/env bash

if [ -e ~/.bash_profile ] ; then
    . ~/.bash_profile
fi

# The next line updates PATH for the Google Cloud SDK.
source '/home/otrenav/Projects/google_cloud/google-cloud-sdk/path.bash.inc'

# The next line enables bash completion for gcloud.
source '/home/otrenav/Projects/google_cloud/google-cloud-sdk/completion.bash.inc'
