#!/usr/bin/env bash

#
# Aliases
#
alias p='cd ~/Projects; ls;'
alias d='cd ~/Downloads; ls;'
alias grep='grep --color=auto'
alias gg='grep --color=auto -rnwi . -e'
alias file_count='find . -type f | wc -l'

unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then
    double_click='xdg-open'
    alias ls='ls -lGF --color=auto'
    alias lsall='ls -flaF --color=auto'
elif [[ "$unamestr" == 'Darwin' ]]; then
    alias ls='ls -lGF'
    alias lsall='ls -flaF'
    alias start_mysql='launchctl load ~/Library/LaunchAgents/homebrew.mxcl.mysql.plist'
    alias stop_mysql='launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.mysql.plist'
fi

#
# R
#
alias R='R --no-save'
alias r='R --no-save'
export R_PROFILE_USER='~/Projects/system/dotfiles/r/Rprofile'

#
# Bash-It
#
export BASH_IT=$HOME/.bash_it
export BASH_IT_THEME='otrenav'
if [ -e $BASH_IT/bash_it.sh ]; then
    source $BASH_IT/bash_it.sh
fi
HISTCONTROL=ignoredups:ignorespace

#
# Git
#
source ~/Projects/system/dotfiles/git/git-completion.bash

#
# Google Cloud
#
if [ -e ~/Projects/system/google-cloud/completion.bash.inc ]; then
    source ~/Projects/system/google-cloud/path.bash.inc
    source ~/Projects/system/google-cloud/completion.bash.inc
fi

#
# Emacs
#
if [[ "$unamestr" == 'Linux' ]]; then
    export ALTERNATE_EDITOR=""
    alias emacs="emacsclient -c -n"
    alias emacss="/usr/bin/emacs"
    export EDITOR="emacsclient -c -n"
elif [[ "$unamestr" == 'Darwin' ]]; then
    alias emacs='/Applications/Emacs.app/Contents/MacOS/Emacs'
    export EDITOR="/Applications/Emacs.app/Contents/MacOS/Emacs"
fi

#
# Score Data
#
alias s='cd ~/Projects/datata/score-data/project/; ls;'
function switch_database() {
    echo "[+] Switching database (development) for Score Data..."
    mysql < ~/Projects/system/dotfiles/sql/switch_database.sql
    mysql development < $1
    echo "[+] Done."
}

#
# Python
#
alias kp='killall python'
alias rm_pyc='find . -name "*.pyc" -exec rm {} \;'
export WORKON_HOME=~/Projects/system/python/envs
source `which virtualenvwrapper.sh`

#
# Django
#
alias m='./manage.py'
alias dj='./manage.py runserver'
alias ds='./manage.py shell_plus'
alias rm_migrations='find . -name "000*.py*" -exec rm {} \;'
source ~/Projects/system/dotfiles/bash/scripts/django-bash-completion.bash

#
# Functions
#
function file_directory_size() {
    if du -b /dev/null > /dev/null 2>&1; then
        local arg=-sbh
    else
        local arg=-sh
    fi
    if [[ -n "$@" ]]; then
        du $arg -- "$@"
    else
        du $arg .[^.]* *
    fi
}

function show_keys() {
    gpg $1
    f=$(echo $1 | sed 's/\.[^.]*$//')
    more "${f}"
    rm "${f}"
}

#
# AWS
#
alias dynamodb='java -Djava.library.path=~/Applications/DynamoDB/DynamoDBLocal_lib -jar ~/Applications/DynamoDB/DynamoDBLocal.jar -sharedDb'

#
# CVEST
#
export NODE_PATH=~/Projects/personal/cvest/cvest-app
