#!/usr/bin/env bash

unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then
    export PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/usr/texbin:/bin:/sbin:$PATH
    alias ls='ls -lGF --color=auto'
    alias lsall='ls -flaF --color=auto'
elif [[ "$unamestr" == 'Darwin' ]]; then
    export PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/usr/texbin:/bin:/sbin:/Users/Omar/.local/bin:$PATH
    alias ls='ls -lGF'
    alias lsall='ls -flaF'
    alias R='R --no-save --quite'
    alias r='R --no-save --quite'
    alias matlab='/Applications/MATLAB_R2013a.app/bin/matlab'
    alias photoshop='open -a "Adobe Photoshop CS6"'
fi

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias p='cd ~/Projects; ls;'
alias d='cd ~/Downloads; ls;'
alias gcpm='~/Projects/datata/gcpm/datata_gae_master_script.sh'

export ALTERNATE_EDITOR=emacs
export EDITOR=emacsclient
export VISUAL=emacsclient

export WORKON_HOME=~/Projects/python/envs
export PROJECTS_PATH=~/Projects/itam/research
export BASH_IT=$HOME/.bash_it
export BASH_IT_THEME='otrenav'

export VIRTUALENVWRAPPER_PYTHON=`which python`
export VIRTUALENVWRAPPER_VIRTUALENV=`which virtualenv`
source `which virtualenvwrapper.sh`

source $BASH_IT/bash_it.sh
source ~/Projects/system/dotfiles/bash/scripts/git-completion.bash
source ~/Projects/system/google-cloud-sdk/path.bash.inc
source ~/Projects/system/google-cloud-sdk/completion.bash.inc

HISTCONTROL=ignoredups:ignorespace

# Check window size after each
# command to adjust accordingly
shopt -s checkwinsize

# File/dir size
function fs() {
    if du -b /dev/null > /dev/null 2>&1; then
        local arg=-sbh
    else
        local arg=-sh
    fi
    if [[ -n "$@" ]]; then
        du $arg -- "$@"
    else
        du $arg .[^.]* *
    fi
}

# Update all projects in directory
# GUD := Git Up Directories
function gud() {
    for d in */; do
        echo $d
        cd $d
        git up
        echo " "
        cd ..
    done
}
