#!/usr/bin/env bash

if [ -e ~/.bash.d/bashrc ] ; then
  . ~/.bash.d/bashrc
fi

# Path to the bash it configuration
export BASH_IT=$HOME/.bash_it

# Lock and Load a custom theme file
# location /.bash_it/themes/
export BASH_IT_THEME='minimal'

# Load Bash It
source $BASH_IT/bash_it.sh

# The next line updates PATH for the Google Cloud SDK.
source '/Users/Omar/Projects/google-cloud-sdk/path.bash.inc'

# The next line enables bash completion for gcloud.
source '/Users/Omar/Projects/google-cloud-sdk/completion.bash.inc'
