#!/usr/bin/env bash

alias p='cd ~/Projects; ls;'
alias d='cd ~/Downloads; ls;'
alias grep='grep --color=auto'
alias gg='grep --color=auto -rnwi . -e'
alias file_count='find . -type -f | wc -l'
unamestr=`uname`

if [[ "$unamestr" == 'Linux' ]]; then
    double_click='xdg-open'
    alias lsall='ls -flaF --color=auto'
    alias ls='ls -lGF --color=auto'
elif [[ "$unamestr" == 'Darwin' ]]; then
    alias ls='ls -lGF'
    alias lsall='ls -flaF'
fi

source ~/Projects/system/dotfiles/git/git-completion.bash

function file_directory_size() {
    if du -b /dev/null > /dev/null 2>&1; then
        local arg=-sbh
    else
        local arg=-sh
    fi
    if [[ -n "$@" ]]; then
        du $arg -- "$@"
    else
        du $arg .[^.]* *
    fi
}

function show_keys() {
    gpg $1
    f=$(echo $1 | sed 's/\.[^.]*$//')
    more "${f}"
    rm "${f}"
}
